# Generated by Django 6.0.4 on 2026-07-03 06:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('num_travelers', models.PositiveIntegerField(default=1)),
                ('travel_type', models.CharField(default='Solo', max_length=100)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True)),
                ('itinerary', models.JSONField(blank=True, default=list)),
                ('hotels', models.JSONField(blank=True, default=list)),
                ('restaurants', models.JSONField(blank=True, default=list)),
                ('transport', models.JSONField(blank=True, default=list)),
                ('things_to_do', models.JSONField(blank=True, default=list)),
                ('travel_tips', models.JSONField(blank=True, default=list)),
                ('share_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
