# Generated by Django 6.0.4 on 2026-07-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='packing_list',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
