# Generated by Django 6.0.4 on 2026-07-03 07:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_expense_journalentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_trips', to=settings.AUTH_USER_MODEL),
        ),
    ]
